### ISSUE TITLE
The extra_var_file configuration option does not work

### ISSUE THREAD

**Issue by walterdolce** [neillturner/kitchen-ansible#243]
Hi,
Looks like the `extra_var_file` configuration option does not work, even when the path used in there is specified in the `additional_copy_path` list of paths. Please see my `.kitchen.yml` below.

```
---
transport:
  max_ssh_sessions: 6

driver:
  name: vagrant
  provider: virtualbox

provisioner:
  name: ansible_playbook
  hosts: all
  ansible_vault_password_file: ./vault_passphrase_development
  ansible_verbosity: 4
  ansible_verbose: true
  ansible_version: latest
  ansible_sudo: false
  require_ansible_repo: false
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_pip: true
  requirements_path: ./requirements.yml
  roles_path: ./roles
  additional_copy_role_path: true
  additional_copy_path:
    - ./group_vars
    - ./vault
    - ./vars
    - ./roles_external
   # With or without this, the result will the same. Test-kitchen will error.
    - ./test/integration/suite-name/vars/vars_development.yml

verifier:
  name: inspec

platforms:
  - name: debian
    driver:
      box: debian/jessie64
      box_version: 8.7.0

suites:
  - name: suite-name
    verifier:
      inspec_tests:
        - path: ./test/integration/suite-name/roles/some-other-role
        - path: ./roles/some-role/spec
    provisioner:
      playbook: ./development-app-playbook.yml
      extra_vars_file: test/integration/suite-name/vars/vars_development.yml
```

Relevant output of the `kitchen converge -l debug` command:
```
ANSIBLE_ROLES_PATH=/tmp/kitchen/roles:/tmp/kitchen/group_vars:/tmp/kitchen/vault:/tmp/kitchen/vars:/tmp/kitchen/roles_external:/tmp/kitchen/vars_development.yml ansible-playbook -i /tmp/kitchen/hosts  -c local -M /tmp/kitchen/modules -vvvv   --vault-password-file=/tmp/kitchen/vault_passphrase_development   -e '@test/integration/suite-name/vars/vars_development.yml'   /tmp/kitchen/development-app-playbook.yml
)
       Using /etc/ansible/ansible.cfg as config file
       ERROR! the file_name '/home/vagrant/test/integration/suite-name/vars/vars_development.yml' does not exist, or is not readable
D      Cleaning up local sandbox in /var/folders/y2/7v6ryw5d13vg8pxfkr5p_m280000gn/T/eat-redesign-debian-sandbox-20170516-88528-1jykyk0
```

**Comment by walterdolce** [comment]
This is not working because the provisioner is looking for the `extra_vars_file` in the current user's home folder. 

If I change this as the below then it works.
```
    provisioner:
      playbook: ./development-app-playbook.yml
      # I moved the vars file from the path defined above to the one below
      extra_vars_file: /tmp/kitchen/vars/test-kitchen-suite-name-development.yml

```

Is that expected?

**Comment by aaronlippold** [comment]
I am also having a similar issue with the `vars` file, not sure if I should submit an issue or if I just have misconfigured my .kitchen.yml file.

I am getting the following error:

```
 Installing ansible, will try to determine platform os
       Transferring files to <crunchy-95-unhardened>
       Using /etc/ansible/ansible.cfg as config file
       ERROR! vars file vars/main.yml was not found
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
```
```
[vagrant@crunchy-95-unhardened kitchen]$ ls
ansible.cfg  callback_plugins  default.yml  filter_plugins  group_vars  hosts_vagrant  host_vars  library  lookup_plugins  modules  roles  spec  ssh_private_keys
```
On the vagrant box it has correctly copied the `main.yml` file to the `host_vars` directory, it seems we are not abstracting that and also not coping `vars` and `tasks` directory.

I added the following to the .kitchen.yml file however I wonder if we really should be needing folks to do this kind of debugging.

```
  ansible_version: latest
  ansible_yum_repo: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
  ansible_verbosity: 4
  additional_copy_path:
    - ./tasks
    - ./vars
```

**Comment by neillturner** [comment]
this will be supported when PR additional_copy_path file path expansion when relative path is given. #245 is merged shortly.

**Comment by neillturner** [comment]
closed fixed in version 0.47.0

**Comment by walterdolce** [comment]
@neillturner this is not what I was expecting. `additional_copy_path` is to move over files. `extra_vars_file` instead loads the vars file and gives it absolute precedence over everything else.

Your solution changes the behaviour and also leaves the `extra_vars_file` variable still broken. So this should not be closed in my opinion.

Unless I'm missing something. In that case please help me better understand this.

**Comment by aaronlippold** [comment]
@neillturner this still seems to be an issue for the `extra_vars_file:` param. The above workaournd is still needed.
